// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdgyRL4IPQeYlKPUOoZI7yCc8X5fEF9xY',
    appId: '1:100861769699:android:43af2dfa4cabf2545512d6',
    messagingSenderId: '100861769699',
    projectId: 'audio-to-firebase',
    storageBucket: 'audio-to-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkffdASTd91g73VpCvTK1zren_IHbj2gw',
    appId: '1:100861769699:ios:6174b8fc97ea89b85512d6',
    messagingSenderId: '100861769699',
    projectId: 'audio-to-firebase',
    storageBucket: 'audio-to-firebase.appspot.com',
    androidClientId: '100861769699-buobtralkthri2e8e0t0jk2tvl5hhj86.apps.googleusercontent.com',
    iosClientId: '100861769699-8pc62qfi40db2qnro76jmagenth8i0mk.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioToFirebase',
  );
}
